spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
zuul:
  ribbonIsolationStrategy: THREAD
  threadPool:
    useSeparateThreadPools: true
management:
  security:
    enabled: false
security:
  basic:
    enabled: false